version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=startup.py
      - FLASK_DEBUG=1
      - APP_CONFIG_FILE=config.py
      - TESTING=False
      - SECRET_KEY=
    depends_on:
      - "db"
    ports:
      - 5000:5000
    restart: always
  db:
    image: "postgres:11.5"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_URL=127.0.0.1:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
    - frdDB:/var/lib/postgresql/data
volumes: 
  frdDB:
