version: "3.7"

services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=startup.py
      - FLASK_DEBUG=1
      - APP_CONFIG_FILE=config.py
      - TESTING=True
      - SECRET_KEY=secret_key
      - DB_TYPE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - SQLALCHEMY_DATABASE_URI=None
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
    depends_on:
      - "db"
    ports:
      - 5000:5000
    restart: always
  db:
    container_name: database
    image: "postgres:12.0"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
    - frdDB:/var/lib/postgresql/data
volumes: 
  frdDB:
